Fix typo in docs-latest example-1
wso2-extensions/siddhi-store-redis pull request #29
Opened 2019-09-19 10:41 UTC by Malintha1996

## Purpose
> Fix typo in example 1

2019-09-19 10:46 UTC, niveathika requested changes
This is a generated file at release time, make the changes to Annoation in the java classses

2019-09-19 12:38 UTC, pcnfernando approved these changes

2019-09-24 13:37 UTC, niveathika requested changes

2019-09-24 13:37 UTC, niveathika commented on docs/api/3.1.2-SNAPSHOT.md
> +# API Docs - v3.1.2-SNAPSHOT
Remove this file, it will be generated at release

2019-09-24 14:02 UTC, niveathika approved these changes

2019-09-24 14:02 UTC, merged